# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_negative',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_positive',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
