# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20170105_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=1000),
        ),
    ]
