# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20170105_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
