# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_question_num_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='num_votes',
            new_name='likes',
        ),
    ]
